ALTER TABLE users ADD COLUMN IF NOT EXISTS height_cm NUMERIC;
ALTER TABLE users ADD COLUMN IF NOT EXISTS age INT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS sex VARCHAR(10);
ALTER TABLE users ADD COLUMN IF NOT EXISTS activity_level VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS goal_weight_lbs NUMERIC;
ALTER TABLE users ADD COLUMN IF NOT EXISTS weekly_loss_target NUMERIC DEFAULT 1;

CREATE TABLE IF NOT EXISTS weight_logs (
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES users(id),
  weight_lbs NUMERIC NOT NULL,
  logged_at DATE NOT NULL DEFAULT CURRENT_DATE,
  UNIQUE(user_id, logged_at)
);
